package com.symantec.tree.utilities.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-21T18:27:09.560+05:30
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices/auth", name = "AuthenticationServicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AuthenticationServicePort {

    @WebMethod
    @WebResult(name = "DenyRiskResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "DenyRiskResponse")
    public DenyRiskResponseType denyRisk(
        @WebParam(partName = "DenyRiskRequest", name = "DenyRiskRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        DenyRiskRequestType denyRiskRequest
    );

    @WebMethod
    @WebResult(name = "AuthenticateUserResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "AuthenticateUserResponse")
    public AuthenticateUserResponseType authenticateUser(
        @WebParam(partName = "AuthenticateUserRequest", name = "AuthenticateUserRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        AuthenticateUserRequestType authenticateUserRequest
    );

    @WebMethod
    @WebResult(name = "AuthenticateUserWithPushResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "AuthenticateUserWithPushResponse")
    public AuthenticateUserWithPushResponseType authenticateUserWithPush(
        @WebParam(partName = "AuthenticateUserWithPushRequest", name = "AuthenticateUserWithPushRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        AuthenticateUserWithPushRequestType authenticateUserWithPushRequest
    );

    @WebMethod
    @WebResult(name = "AuthenticateCredentialsResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "AuthenticateCredentialsResponse")
    public AuthenticateCredentialsResponseType authenticateCredentials(
        @WebParam(partName = "AuthenticateCredentialsRequest", name = "AuthenticateCredentialsRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        AuthenticateCredentialsRequestType authenticateCredentialsRequest
    );

    @WebMethod
    @WebResult(name = "EvaluateRiskResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "EvaluateRiskResponse")
    public EvaluateRiskResponseType evaluateRisk(
        @WebParam(partName = "EvaluateRiskRequest", name = "EvaluateRiskRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        EvaluateRiskRequestType evaluateRiskRequest
    );

    @WebMethod
    @WebResult(name = "CheckOtpResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "CheckOtpResponse")
    public CheckOtpResponseType checkOtp(
        @WebParam(partName = "CheckOtpRequest", name = "CheckOtpRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        CheckOtpRequestType checkOtpRequest
    );

    @WebMethod
    @WebResult(name = "ConfirmRiskResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "ConfirmRiskResponse")
    public ConfirmRiskResponseType confirmRisk(
        @WebParam(partName = "ConfirmRiskRequest", name = "ConfirmRiskRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        ConfirmRiskRequestType confirmRiskRequest
    );
}
