package com.symantec.tree.utilities.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-21T18:27:09.597+05:30
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "AuthenticationService",
                  wsdlLocation = "file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir8294278991621167300.tmp/vipuserservices-auth-1.8_1.wsdl",
                  targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices/auth")
public class AuthenticationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://schemas.symantec.com/vip/2011/04/vipuserservices/auth", "AuthenticationService");
    public final static QName AuthenticationServicePort = new QName("https://schemas.symantec.com/vip/2011/04/vipuserservices/auth", "AuthenticationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir8294278991621167300.tmp/vipuserservices-auth-1.8_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthenticationService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir8294278991621167300.tmp/vipuserservices-auth-1.8_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthenticationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthenticationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AuthenticationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthenticationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthenticationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AuthenticationServicePort
     */
    @WebEndpoint(name = "AuthenticationServicePort")
    public AuthenticationServicePort getAuthenticationServicePort() {
        return super.getPort(AuthenticationServicePort, AuthenticationServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationServicePort
     */
    @WebEndpoint(name = "AuthenticationServicePort")
    public AuthenticationServicePort getAuthenticationServicePort(WebServiceFeature... features) {
        return super.getPort(AuthenticationServicePort, AuthenticationServicePort.class, features);
    }

}
