package com.symantec.tree.utilities.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-21T18:27:31.378+05:30
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "ManagementService",
                  wsdlLocation = "file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir2855310298772730702.tmp/vipuserservices-mgmt-1.8_1.wsdl",
                  targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices/mgmt")
public class ManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://schemas.symantec.com/vip/2011/04/vipuserservices/mgmt", "ManagementService");
    public final static QName ManagementServicePort = new QName("https://schemas.symantec.com/vip/2011/04/vipuserservices/mgmt", "ManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir2855310298772730702.tmp/vipuserservices-mgmt-1.8_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ManagementService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir2855310298772730702.tmp/vipuserservices-mgmt-1.8_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ManagementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ManagementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ManagementServicePort
     */
    @WebEndpoint(name = "ManagementServicePort")
    public ManagementServicePort getManagementServicePort() {
        return super.getPort(ManagementServicePort, ManagementServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManagementServicePort
     */
    @WebEndpoint(name = "ManagementServicePort")
    public ManagementServicePort getManagementServicePort(WebServiceFeature... features) {
        return super.getPort(ManagementServicePort, ManagementServicePort.class, features);
    }

}
