package com.symantec.tree.utilities.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-21T18:27:31.340+05:30
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices/mgmt", name = "ManagementServicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ManagementServicePort {

    @WebMethod
    @WebResult(name = "SetTemporaryPasswordAttributesResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "SetTemporaryPasswordAttributesResponse")
    public SetTemporaryPasswordAttributesResponseType setTemporaryPasswordAttributes(
        @WebParam(partName = "SetTemporaryPasswordAttributesRequest", name = "SetTemporaryPasswordAttributesRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        SetTemporaryPasswordAttributesRequestType setTemporaryPasswordAttributesRequest
    );

    @WebMethod
    @WebResult(name = "SendOtpResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "SendOtpResponse")
    public SendOtpResponseType sendOtp(
        @WebParam(partName = "SendOtpRequest", name = "SendOtpRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        SendOtpRequestType sendOtpRequest
    );

    @WebMethod
    @WebResult(name = "UpdateCredentialResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "UpdateCredentialResponse")
    public UpdateCredentialResponseType updateCredential(
        @WebParam(partName = "UpdateCredentialRequest", name = "UpdateCredentialRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        UpdateCredentialRequestType updateCredentialRequest
    );

    @WebMethod
    @WebResult(name = "SetTemporaryPasswordResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "SetTemporaryPasswordResponse")
    public SetTemporaryPasswordResponseType setTemporaryPassword(
        @WebParam(partName = "SetTemporaryPasswordRequest", name = "SetTemporaryPasswordRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        SetTemporaryPasswordRequestType setTemporaryPasswordRequest
    );

    @WebMethod
    @WebResult(name = "AddCredentialResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "AddCredentialResponse")
    public AddCredentialResponseType addCredential(
        @WebParam(partName = "AddCredentialRequest", name = "AddCredentialRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        AddCredentialRequestType addCredentialRequest
    );

    @WebMethod
    @WebResult(name = "RemoveCredentialResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "RemoveCredentialResponse")
    public RemoveCredentialResponseType removeCredential(
        @WebParam(partName = "RemoveCredentialRequest", name = "RemoveCredentialRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        RemoveCredentialRequestType removeCredentialRequest
    );

    @WebMethod
    @WebResult(name = "UpdateUserResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "UpdateUserResponse")
    public UpdateUserResponseType updateUser(
        @WebParam(partName = "UpdateUserRequest", name = "UpdateUserRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        UpdateUserRequestType updateUserRequest
    );

    @WebMethod
    @WebResult(name = "ClearUserPinResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "ClearUserPinResponse")
    public ClearUserPinResponseType clearUserPin(
        @WebParam(partName = "ClearUserPinRequest", name = "ClearUserPinRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        ClearUserPinRequestType clearUserPinRequest
    );

    @WebMethod
    @WebResult(name = "ClearTemporaryPasswordResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "ClearTemporaryPasswordResponse")
    public ClearTemporaryPasswordResponseType clearTemporaryPassword(
        @WebParam(partName = "ClearTemporaryPasswordRequest", name = "ClearTemporaryPasswordRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        ClearTemporaryPasswordRequestType clearTemporaryPasswordRequest
    );

    @WebMethod
    @WebResult(name = "RegisterResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "RegisterResponse")
    public RegisterResponseType register(
        @WebParam(partName = "RegisterRequest", name = "RegisterRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        RegisterRequestType registerRequest
    );

    @WebMethod
    @WebResult(name = "DeleteUserResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "DeleteUserResponse")
    public DeleteUserResponseType deleteUser(
        @WebParam(partName = "DeleteUserRequest", name = "DeleteUserRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        DeleteUserRequestType deleteUserRequest
    );

    @WebMethod
    @WebResult(name = "CreateUserResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "CreateUserResponse")
    public CreateUserResponseType createUser(
        @WebParam(partName = "CreateUserRequest", name = "CreateUserRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        CreateUserRequestType createUserRequest
    );
}
