package com.symantec.tree.utilities.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-21T18:27:57.682+05:30
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices/query", name = "QueryServicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueryServicePort {

    @WebMethod
    @WebResult(name = "GetCredentialInfoResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "GetCredentialInfoResponse")
    public GetCredentialInfoResponseType getCredentialInfo(
        @WebParam(partName = "GetCredentialInfoRequest", name = "GetCredentialInfoRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        GetCredentialInfoRequestType getCredentialInfoRequest
    );

    @WebMethod
    @WebResult(name = "GetUserInfoResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "GetUserInfoResponse")
    public GetUserInfoResponseType getUserInfo(
        @WebParam(partName = "GetUserInfoRequest", name = "GetUserInfoRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        GetUserInfoRequestType getUserInfoRequest
    );

    @WebMethod
    @WebResult(name = "GetServerTimeResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "GetServerTimeResponse")
    public GetServerTimeResponseType getServerTime(
        @WebParam(partName = "GetServerTimeRequest", name = "GetServerTimeRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        GetServerTimeRequestType getServerTimeRequest
    );

    @WebMethod
    @WebResult(name = "PollPushStatusResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "PollPushStatusResponse")
    public PollPushStatusResponseType pollPushStatus(
        @WebParam(partName = "PollPushStatusRequest", name = "PollPushStatusRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        PollPushStatusRequestType pollPushStatusRequest
    );

    @WebMethod
    @WebResult(name = "GetTemporaryPasswordAttributesResponse", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices", partName = "GetTemporaryPasswordAttributesResponse")
    public GetTemporaryPasswordAttributesResponseType getTemporaryPasswordAttributes(
        @WebParam(partName = "GetTemporaryPasswordAttributesRequest", name = "GetTemporaryPasswordAttributesRequest", targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices")
        GetTemporaryPasswordAttributesRequestType getTemporaryPasswordAttributesRequest
    );
}
