package com.symantec.tree.utilities.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-21T18:27:57.719+05:30
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "QueryService",
                  wsdlLocation = "file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir6747764755867892118.tmp/vipuserservices-query-1.8_1.wsdl",
                  targetNamespace = "https://schemas.symantec.com/vip/2011/04/vipuserservices/query")
public class QueryService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://schemas.symantec.com/vip/2011/04/vipuserservices/query", "QueryService");
    public final static QName QueryServicePort = new QName("https://schemas.symantec.com/vip/2011/04/vipuserservices/query", "QueryServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir6747764755867892118.tmp/vipuserservices-query-1.8_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir6747764755867892118.tmp/vipuserservices-query-1.8_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public QueryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns QueryServicePort
     */
    @WebEndpoint(name = "QueryServicePort")
    public QueryServicePort getQueryServicePort() {
        return super.getPort(QueryServicePort, QueryServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryServicePort
     */
    @WebEndpoint(name = "QueryServicePort")
    public QueryServicePort getQueryServicePort(WebServiceFeature... features) {
        return super.getPort(QueryServicePort, QueryServicePort.class, features);
    }

}
