package com.symantec.tree.utilities.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-21T18:26:28.210+05:30
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "vipSoapInterfaceService",
                  wsdlLocation = "file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir5699383561188027748.tmp/vip_auth_1.wsdl",
                  targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
public class VipSoapInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://schemas.vip.symantec.com/2006/08/vipservice", "vipSoapInterfaceService");
    public final static QName VipServiceAPI = new QName("https://schemas.vip.symantec.com/2006/08/vipservice", "vipServiceAPI");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir5699383561188027748.tmp/vip_auth_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VipSoapInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/bprayaga/AppData/Local/Temp/tempdir5699383561188027748.tmp/vip_auth_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VipSoapInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VipSoapInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VipSoapInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VipSoapInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VipSoapInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VipSoapInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns VipSoapInterface
     */
    @WebEndpoint(name = "vipServiceAPI")
    public VipSoapInterface getVipServiceAPI() {
        return super.getPort(VipServiceAPI, VipSoapInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VipSoapInterface
     */
    @WebEndpoint(name = "vipServiceAPI")
    public VipSoapInterface getVipServiceAPI(WebServiceFeature... features) {
        return super.getPort(VipServiceAPI, VipSoapInterface.class, features);
    }

}
