package com.symantec.tree.utilities.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-21T18:26:28.162+05:30
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", name = "vipSoapInterface")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VipSoapInterface {

    @WebMethod(operationName = "UnlockToken")
    @WebResult(name = "UnlockTokenResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "UnlockTokenResponse")
    public UnlockTokenResponseType unlockToken(
        @WebParam(partName = "UnlockToken", name = "UnlockToken", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        UnlockTokenType unlockToken
    );

    @WebMethod(operationName = "VerifyTxnOTP")
    @WebResult(name = "VerifyTxnOTPResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "VerifyTxnOTPResponse")
    public VerifyTxnOTPResponseType verifyTxnOTP(
        @WebParam(partName = "VerifyTxnOTP", name = "VerifyTxnOTP", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        VerifyTxnOTPType verifyTxnOTP
    );

    @WebMethod(operationName = "PollTxnVerification")
    @WebResult(name = "PollTxnVerificationResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "PollTxnVerificationResponse")
    public PollTxnVerificationResponseType pollTxnVerification(
        @WebParam(partName = "PollTxnVerification", name = "PollTxnVerification", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        PollTxnVerificationType pollTxnVerification
    );

    @WebMethod(operationName = "GetServerTime")
    @WebResult(name = "GetServerTimeResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "GetServerTimeResponse")
    public GetServerTimeResponseType getServerTime(
        @WebParam(partName = "GetServerTime", name = "GetServerTime", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        GetServerTimeType getServerTime
    );

    @WebMethod(operationName = "Synchronize")
    @WebResult(name = "SynchronizeResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "SynchronizeResponse")
    public SynchronizeResponseType synchronize(
        @WebParam(partName = "Synchronize", name = "Synchronize", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        SynchronizeType synchronize
    );

    @WebMethod(operationName = "GetTokenInformation")
    @WebResult(name = "GetTokenInformationResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "GetTokenInformationResponse")
    public GetTokenInformationResponseType getTokenInformation(
        @WebParam(partName = "GetTokenInformation", name = "GetTokenInformation", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        GetTokenInformationType getTokenInformation
    );

    @WebMethod(operationName = "DeliverTxnOTP")
    @WebResult(name = "DeliverTxnOTPResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "DeliverTxnOTPResponse")
    public DeliverTxnOTPResponseType deliverTxnOTP(
        @WebParam(partName = "DeliverTxnOTP", name = "DeliverTxnOTP", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        DeliverTxnOTPType deliverTxnOTP
    );

    @WebMethod(operationName = "Validate")
    @WebResult(name = "ValidateResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "ValidateResponse")
    public ValidateResponseType validate(
        @WebParam(partName = "Validate", name = "Validate", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        ValidateType validate
    );

    @WebMethod(operationName = "CheckOTP")
    @WebResult(name = "CheckOTPResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "CheckOTPResponse")
    public CheckOTPResponseType checkOTP(
        @WebParam(partName = "CheckOTP", name = "CheckOTP", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        CheckOTPType checkOTP
    );

    @WebMethod(operationName = "ValidateCR")
    @WebResult(name = "ValidateCRResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "ValidateCRResponse")
    public ValidateCRResponseType validateCR(
        @WebParam(partName = "ValidateCR", name = "ValidateCR", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        ValidateCRType validateCR
    );

    @WebMethod(operationName = "SendOTP")
    @WebResult(name = "SendOTPResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "SendOTPResponse")
    public SendOTPResponseType sendOTP(
        @WebParam(partName = "SendOTP", name = "SendOTP", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        SendOTPType sendOTP
    );

    @WebMethod(operationName = "DeliverSMS")
    @WebResult(name = "DeliverSMSResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "DeliverSMSResponse")
    public DeliverSMSResponseType deliverSMS(
        @WebParam(partName = "DeliverSMS", name = "DeliverSMS", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        DeliverSMSType deliverSMS
    );

    @WebMethod(operationName = "SetTemporaryPassword")
    @WebResult(name = "SetTemporaryPasswordResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "SetTemporaryPasswordResponse")
    public SetTemporaryPasswordResponseType setTemporaryPassword(
        @WebParam(partName = "SetTemporaryPassword", name = "SetTemporaryPassword", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        SetTemporaryPasswordType setTemporaryPassword
    );

    @WebMethod(operationName = "SendTemporaryPassword")
    @WebResult(name = "SendTemporaryPasswordResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "SendTemporaryPasswordResponse")
    public SendTemporaryPasswordResponseType sendTemporaryPassword(
        @WebParam(partName = "SendTemporaryPassword", name = "SendTemporaryPassword", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        SendTemporaryPasswordType sendTemporaryPassword
    );

    @WebMethod(operationName = "GetAdapterConfiguration")
    @WebResult(name = "GetAdapterConfigurationResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "GetAdapterConfigurationResponse")
    public GetAdapterConfigurationResponseType getAdapterConfiguration(
        @WebParam(partName = "GetAdapterConfiguration", name = "GetAdapterConfiguration", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        GetAdapterConfigurationType getAdapterConfiguration
    );

    @WebMethod(operationName = "SetAdapterConfiguration")
    @WebResult(name = "SetAdapterConfigurationResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "SetAdapterConfigurationResponse")
    public SetAdapterConfigurationResponseType setAdapterConfiguration(
        @WebParam(partName = "SetAdapterConfiguration", name = "SetAdapterConfiguration", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        SetAdapterConfigurationType setAdapterConfiguration
    );

    @WebMethod(operationName = "Register")
    @WebResult(name = "RegisterResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "RegisterResponse")
    public RegisterResponseType register(
        @WebParam(partName = "Register", name = "Register", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        RegisterType register
    );

    @WebMethod(operationName = "EnableToken")
    @WebResult(name = "EnableTokenResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "EnableTokenResponse")
    public EnableTokenResponseType enableToken(
        @WebParam(partName = "EnableToken", name = "EnableToken", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        EnableTokenType enableToken
    );

    @WebMethod(operationName = "GetTemporaryPwdExpiration")
    @WebResult(name = "GetTemporaryPwdExpirationResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "GetTemporaryPwdExpirationResponse")
    public GetTemporaryPwdExpirationResponseType getTemporaryPwdExpiration(
        @WebParam(partName = "GetTemporaryPwdExpiration", name = "GetTemporaryPwdExpiration", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        GetTemporaryPwdExpirationType getTemporaryPwdExpiration
    );

    @WebMethod(operationName = "SubmitTxnVerification")
    @WebResult(name = "SubmitTxnVerificationResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "SubmitTxnVerificationResponse")
    public SubmitTxnVerificationResponseType submitTxnVerification(
        @WebParam(partName = "SubmitTxnVerification", name = "SubmitTxnVerification", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        SubmitTxnVerificationType submitTxnVerification
    );

    @WebMethod(operationName = "ActivateToken")
    @WebResult(name = "ActivateTokenResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "ActivateTokenResponse")
    public ActivateTokenResponseType activateToken(
        @WebParam(partName = "ActivateToken", name = "ActivateToken", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        ActivateTokenType activateToken
    );

    @WebMethod(operationName = "SetTokenAttributes")
    @WebResult(name = "SetTokenAttributesResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "SetTokenAttributesResponse")
    public SetTokenAttributesResponseType setTokenAttributes(
        @WebParam(partName = "SetTokenAttributes", name = "SetTokenAttributes", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        SetTokenAttributesType setTokenAttributes
    );

    @WebMethod(operationName = "ValidateMultiple")
    @WebResult(name = "ValidateMultipleResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "ValidateMultipleResponse")
    public ValidateMultipleResponseType validateMultiple(
        @WebParam(partName = "ValidateMultiple", name = "ValidateMultiple", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        ValidateMultipleType validateMultiple
    );

    @WebMethod(operationName = "GenerateTemporaryPassword")
    @WebResult(name = "GenerateTemporaryPasswordResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "GenerateTemporaryPasswordResponse")
    public GenerateTemporaryPasswordResponseType generateTemporaryPassword(
        @WebParam(partName = "GenerateTemporaryPassword", name = "GenerateTemporaryPassword", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        GenerateTemporaryPasswordType generateTemporaryPassword
    );

    @WebMethod(operationName = "SetTemporaryPwdExpiration")
    @WebResult(name = "SetTemporaryPwdExpirationResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "SetTemporaryPwdExpirationResponse")
    public SetTemporaryPwdExpirationResponseType setTemporaryPwdExpiration(
        @WebParam(partName = "SetTemporaryPwdExpiration", name = "SetTemporaryPwdExpiration", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        SetTemporaryPwdExpirationType setTemporaryPwdExpiration
    );

    @WebMethod(operationName = "GetAdminCode")
    @WebResult(name = "GetAdminCodeResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "GetAdminCodeResponse")
    public GetAdminCodeResponseType getAdminCode(
        @WebParam(partName = "GetAdminCode", name = "GetAdminCode", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        GetAdminCodeType getAdminCode
    );

    @WebMethod(operationName = "DeactivateToken")
    @WebResult(name = "DeactivateTokenResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "DeactivateTokenResponse")
    public DeactivateTokenResponseType deactivateToken(
        @WebParam(partName = "DeactivateToken", name = "DeactivateToken", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        DeactivateTokenType deactivateToken
    );

    @WebMethod(operationName = "DisableToken")
    @WebResult(name = "DisableTokenResponse", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice", partName = "DisableTokenResponse")
    public DisableTokenResponseType disableToken(
        @WebParam(partName = "DisableToken", name = "DisableToken", targetNamespace = "https://schemas.vip.symantec.com/2006/08/vipservice")
        DisableTokenType disableToken
    );
}
